# SPDX-FileCopyrightText: 2026 European Centre for Medium-Range Weather Forecasts (ECMWF)
# SPDX-License-Identifier: Apache-2.0
"""The bundled station index is generated from WMO OSCAR/Surface (`make references`)."""

import csv
import json

import regenerate_references as rr
from conftest import FIXTURES, SKILLS

OSCAR = json.loads((FIXTURES / "obs-oscar-synopland.json").read_text())["stationSearchResults"]
INDEX = SKILLS / "ecmwf-observations" / "references" / "stations.csv"


def _rows(text):
    return list(csv.DictReader(line for line in text.splitlines() if not line.startswith("#")))


def test_render_keeps_wmo_ids_of_stations_that_are_not_closed():
    rows = _rows(rr.render_stations(OSCAR))
    ids = [r["wmo"] for r in rows]
    assert ids == sorted(ids) and "08535" in ids and "10384" in ids
    assert "08579" not in ids  # LISBOA/GAGO COUTINHO is closed
    lisbon = next(r for r in rows if r["wmo"] == "08535")
    assert lisbon == {
        "wmo": "08535",
        "name": "LISBOA/GEOFISICO",
        "lat": "38.719",
        "lon": "-9.150",
        "elevation": "77",
        "territory": "Portugal",
    }
    # stations without a WMO (0-20000-0-NNNNN) identifier are not in the index
    assert len(rows) == 2


def test_render_is_marked_generated_and_deterministic():
    text = rr.render_stations(OSCAR)
    assert text.startswith("# GENERATED by scripts/regenerate_references.py")
    assert text == rr.render_stations(list(reversed(OSCAR)))


def test_bundled_index_has_the_generated_shape():
    text = INDEX.read_text()
    assert text.startswith("# GENERATED")
    rows = _rows(text)
    assert list(rows[0]) == ["wmo", "name", "lat", "lon", "elevation", "territory"]
    assert all(len(r["wmo"]) == 5 and r["wmo"].isdigit() for r in rows)
