# SPDX-FileCopyrightText: 2026 European Centre for Medium-Range Weather Forecasts (ECMWF)
# SPDX-License-Identifier: Apache-2.0
"""Generate docs/skills.md — the skill catalogue — from every SKILL.md (single source of truth).

python3 scripts/gen_docs.py            # write docs/skills.md
python3 scripts/gen_docs.py --check    # exit 1 if docs/skills.md is stale
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKILLS = ROOT / "plugins" / "ecmwf-weather" / "skills"
OUT = ROOT / "docs" / "skills.md"
# REUSE-IgnoreStart — a licence header written into generated output, not this file's
HEADER = (
    "<!--\n"
    "SPDX-FileCopyrightText: 2026 European Centre for Medium-Range Weather Forecasts (ECMWF)\n"
    "SPDX-License-Identifier: Apache-2.0\n"
    "GENERATED by scripts/gen_docs.py from each SKILL.md — run `make docs`, do not edit.\n"
    "-->\n"
)
# REUSE-IgnoreEnd


def _frontmatter(text: str) -> dict[str, str]:
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    return dict(re.findall(r"^([a-z_]+):\s*(.*)$", m.group(1), re.M)) if m else {}


def _first_line(path: Path) -> str:
    """First line of a script's module docstring, or a reference file's first heading."""
    text = path.read_text()
    if path.suffix == ".py":
        m = re.search(r'^"""(.*?)$', text, re.M)
        return m.group(1).strip().rstrip(".") if m else ""
    m = re.search(r"^# (.+)$", text, re.M)
    return m.group(1).strip() if m else ""


def render(skills: Path = SKILLS) -> str:
    lines = [
        HEADER,
        "# Skill catalogue",
        "",
        "One section per skill: what it does, its helper scripts and its reference files.",
        "Agents read `SKILL.md` first; this page is for humans browsing the repository.",
        "",
        "## Contents",
        "",
    ]
    dirs = sorted(d for d in skills.iterdir() if (d / "SKILL.md").exists())
    lines += [f"- [`{d.name}`](#{d.name})" for d in dirs] + [""]
    for d in dirs:
        fm = _frontmatter((d / "SKILL.md").read_text())
        lines += [f"## `{d.name}`", "", fm.get("description", ""), ""]
        if fm.get("compatibility"):
            lines += [f"**Requirements:** {fm['compatibility']}", ""]
        rel = f"../plugins/ecmwf-weather/skills/{d.name}"
        lines += [f"Source: [`{rel}/SKILL.md`]({rel}/SKILL.md)", ""]
        for kind in ("scripts", "references"):
            files = sorted(p for p in (d / kind).glob("*") if p.suffix in (".py", ".md"))
            if files:
                lines += [f"| {kind.capitalize()[:-1]} | Purpose |", "|---|---|"]
                lines += [f"| `{kind}/{p.name}` | {_first_line(p)} |" for p in files]
                lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text = render()
    if a.check:
        stale = not OUT.exists() or OUT.read_text() != text
        print("docs/skills.md is stale — run `make docs`" if stale else "docs up to date")
        return 1 if stale else 0
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
