#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2026 European Centre for Medium-Range Weather Forecasts (ECMWF)
#
# SPDX-License-Identifier: Apache-2.0

"""Regenerate reference files from live ECMWF catalogues. Never hand-edit the outputs.

  python3 scripts/regenerate_references.py            # rewrite in place
  python3 scripts/regenerate_references.py --check    # exit 1 on drift, write nothing
  python3 scripts/regenerate_references.py --only versions

Outputs (each starts with a GENERATED marker):
  ecmwf-open-data/references/fields.md
      latest IFS + AIFS step-24 .index + ECMWF parameter database
  ecmwf-opencharts-wms/references/layer-catalog.md
      ecCharts WMS GetCapabilities (names, titles, styles)
  ecmwf-earthkit/references/versions.md
      PyPI latest versions of earthkit components and clients
  ecmwf-observations/references/stations.csv
      WMO land stations (WIGOS 0-20000-0-<WMO id>) from WMO OSCAR/Surface, not closed
Volatile facts (valid times, run dates) are left out so files only change when catalogues do.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKILLS = ROOT / "plugins" / "ecmwf-weather" / "skills"
PARAMDB = "https://codes.ecmwf.int/parameter-database/api/v1"
OSCAR_SYNOP = "https://oscar.wmo.int/surface/rest/api/search/station?stationClass=synopLand"
UA = {"User-Agent": "ecmwf-weather-skills-regen/0.1"}
EARTHKIT = [
    "earthkit-data",
    "earthkit-geo",
    "earthkit-meteo",
    "earthkit-utils",
    "earthkit-transforms",
    "earthkit-plots",
    "earthkit-hydro",
    "earthkit-regrid",
    "earthkit-time",
    "earthkit-climate",
    "earthkit-workflows",
]
CLIENTS = [
    "thermofeel",
    "ecmwf-opendata",
    "polytope-client",
    "covjsonkit",
    "cdsapi",
    "ecmwf-api-client",
]
# Below 1.0 but allowed, pinned exactly: date logic nothing else covers.
ALLOWED_EXCEPTIONS = {"earthkit-time": "Emerging — allowed exception, pin exactly"}
DEPRECATED = {
    "earthkit-regrid": "use earthkit-geo",
    "earthkit-maps": "use earthkit-plots",
    "earthkit-aggregate": "use earthkit-transforms",
}
# REUSE-IgnoreStart — a licence header written into generated output, not this file's
HEADER = (
    "<!--\n"
    "SPDX-FileCopyrightText: 2026 European Centre for Medium-Range Weather Forecasts (ECMWF)\n"
    "SPDX-License-Identifier: Apache-2.0\n"
    "GENERATED by scripts/regenerate_references.py — do not edit by hand.\n"
    "-->\n"
)
# REUSE-IgnoreEnd


def _load(skill: str, name: str):
    spec = importlib.util.spec_from_file_location(name, SKILLS / skill / "scripts" / f"{name}.py")
    assert spec and spec.loader
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


def _get(url: str):
    with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=120) as r:
        return json.loads(r.read())


def _cell(s) -> str:
    return str(s or "").replace("|", "\\|").replace("\n", " ")


# --- renderers (pure) -----------------------------------------------------------------------------


def render_fields(models: dict, paramdb: dict) -> str:
    lines = (
        [
            HEADER,
            "# Open Data fields",
            "",
            "Parameters published at step 24, by model and level type. Regenerated weekly.",
            "",
            "## Contents",
        ]
        + [f"- {m}" for m in models]
        + [""]
    )
    for model, s in models.items():
        lines += [f"## {model}", ""]
        # Sorted so the output depends only on the catalogue, not on upstream index order.
        for levtype, params in sorted(s["params"].items()):
            lines += [
                f"### levtype `{levtype}`",
                "",
                "| Short name | Name | Units |",
                "|---|---|---|",
            ]
            for p in sorted(params):
                info = paramdb.get(p, {})
                lines.append(
                    f"| `{p}` | {_cell(info.get('name', '?'))} | {_cell(info.get('units', '?'))} |"
                )
            lines.append("")
        if s.get("pressure_levels"):
            lines += [
                f"Pressure levels (hPa): {', '.join(map(str, s['pressure_levels']))}",
                "",
            ]
        if s.get("soil_levels"):
            lines += [f"Soil layers: {', '.join(map(str, s['soil_levels']))}", ""]
    return "\n".join(lines).rstrip() + "\n"


def render_layers(layers: list[dict]) -> str:
    groups = {
        "Public met layers": [],
        "CAMS composition layers": [],
        "Other layers": [],
    }
    for layer in sorted(layers, key=lambda x: x["name"]):
        key = (
            "Public met layers"
            if layer["name"].endswith("_public")
            else "CAMS composition layers"
            if layer["name"].startswith("composition_")
            else "Other layers"
        )
        groups[key].append(layer)
    lines = (
        [
            HEADER,
            "# WMS layer catalogue",
            "",
            "All layers in https://eccharts.ecmwf.int/wms/?token=public GetCapabilities. "
            "Valid times: `wms.py times --layer NAME`. Regenerated weekly.",
            "",
            "## Contents",
        ]
        + [f"- {g} ({len(v)})" for g, v in groups.items()]
        + [""]
    )
    for g, ls in groups.items():
        lines += [
            f"## {g}",
            "",
            "| Name | Title | Time | Default style |",
            "|---|---|---|---|",
        ]
        for layer in ls:
            style = f"`{layer['styles'][0]['name']}`" if layer["styles"] else ""
            has_time = "yes" if layer["time"] else "no"
            lines.append(f"| `{layer['name']}` | {_cell(layer['title'])} | {has_time} | {style} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _major(v: str) -> int:
    try:
        return int(v.split(".")[0])
    except ValueError:
        return 0


def render_versions(info: dict) -> str:
    lines = [
        HEADER,
        "# earthkit components and ECMWF clients — latest versions",
        "",
        "Only earthkit components with version ≥ 1.0 may be used (see SKILL.md). "
        "Regenerated weekly from PyPI; when a `no` turns `yes`, review it for adoption.",
        "",
        "| Package | Latest | ≥ 1.0 | Note |",
        "|---|---|---|---|",
    ]
    for pkg, ver in info.items():
        if pkg.startswith("earthkit"):
            ok, note = ("yes" if _major(ver) >= 1 else "no"), DEPRECATED.get(pkg, "")
            if pkg in ALLOWED_EXCEPTIONS:
                ok, note = "exception", ALLOWED_EXCEPTIONS[pkg]
        else:
            ok = "n/a"
            note = "client library — the ≥ 1.0 rule applies to earthkit components only"
        lines.append(f"| `{pkg}` | {ver} | {ok} | {note} |")
    return "\n".join(lines) + "\n"


def render_stations(results: list[dict]) -> str:
    """WMO land stations as CSV: one row per WMO id (WIGOS 0-20000-0-NNNNN), closed ones left
    out, sorted by id; coordinates rounded to ~100 m so the file changes only with the registry."""
    import csv
    import io
    import re

    rows = {}
    for s in results:
        if s.get("stationStatusCode") == "closed":
            continue
        for w in s.get("wigosStationIdentifiers", []):
            m = re.fullmatch(r"0-20000-0-(\d{5})", w.get("wigosStationIdentifier", ""))
            if m and m.group(1) not in rows:
                elev = s.get("elevation")
                rows[m.group(1)] = [
                    m.group(1),
                    " ".join(str(s.get("name", "")).split()),
                    f"{float(s['latitude']):.3f}",
                    f"{float(s['longitude']):.3f}",
                    "" if elev is None else f"{float(elev):g}",
                    s.get("territory", ""),
                ]
    buf = io.StringIO()
    buf.write(
        "# GENERATED by scripts/regenerate_references.py from WMO OSCAR/Surface "
        "(https://oscar.wmo.int/surface) — do not edit by hand.\n"
    )
    w = csv.writer(buf, lineterminator="\n")
    w.writerow(["wmo", "name", "lat", "lon", "elevation", "territory"])
    w.writerows(rows[k] for k in sorted(rows))
    return buf.getvalue()


def write_or_check(outputs: dict, check: bool) -> list[Path]:
    drift = []
    for path, text in outputs.items():
        path = Path(path)
        if not path.exists() or path.read_text() != text:
            drift.append(path)
            if not check:
                path.write_text(text)
    return drift


# --- fetchers -------------------------------------------------------------------------------------


def fetch_paramdb() -> dict:
    units = {u["id"]: u.get("name") for u in _get(f"{PARAMDB}/unit/?format=json")}
    out: dict = {}
    for p in sorted(_get(f"{PARAMDB}/param/?format=json"), key=lambda p: p["id"]):
        sn = p.get("shortname")
        if sn and sn not in out:
            out[sn] = {"name": p.get("name"), "units": units.get(p.get("unit_id"), "")}
    return out


def fetch_fields() -> dict:
    od = _load("ecmwf-open-data", "odcatalog")
    models = {}
    for model in ("ifs", "aifs-single"):
        # Latest complete run (final step published), so the catalogue describes a fully
        # published run rather than one still arriving.
        run = od.latest_run(model, "oper")
        entries = od.parse_index(od.fetch_text(od.file_url(run, model, "oper", 24, ext="index")))
        models[model] = od.summarise_fields(entries)
    return models


def fetch_layers() -> list:
    wms = _load("ecmwf-opencharts-wms", "wms")
    url = wms._url({"service": "WMS", "version": "1.3.0", "request": "GetCapabilities"}, "public")
    return wms.parse_capabilities(wms.fetch(url)[1].decode())


def fetch_versions() -> dict:
    return {
        p: _get(f"https://pypi.org/pypi/{p}/json")["info"]["version"] for p in EARTHKIT + CLIENTS
    }


def fetch_stations() -> list[dict]:
    return _get(OSCAR_SYNOP)["stationSearchResults"]


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--check", action="store_true")
    kinds = ["fields", "layers", "versions", "stations"]
    ap.add_argument("--only", choices=kinds, action="append")
    a = ap.parse_args()
    only = set(a.only or kinds)
    outputs = {}
    if "fields" in only:
        outputs[SKILLS / "ecmwf-open-data/references/fields.md"] = render_fields(
            fetch_fields(), fetch_paramdb()
        )
    if "layers" in only:
        outputs[SKILLS / "ecmwf-opencharts-wms/references/layer-catalog.md"] = render_layers(
            fetch_layers()
        )
    if "versions" in only:
        outputs[SKILLS / "ecmwf-earthkit/references/versions.md"] = render_versions(
            fetch_versions()
        )
    if "stations" in only:
        outputs[SKILLS / "ecmwf-observations/references/stations.csv"] = render_stations(
            fetch_stations()
        )
    drift = write_or_check(outputs, a.check)
    for d in drift:
        print(f"{'drift' if a.check else 'updated'}: {d.relative_to(ROOT)}")
    print(
        "no changes"
        if not drift
        else f"{len(drift)} file(s) {'drifted' if a.check else 'regenerated'}"
    )
    return 1 if (a.check and drift) else 0


if __name__ == "__main__":
    sys.exit(main())
