# SPDX-FileCopyrightText: 2026 European Centre for Medium-Range Weather Forecasts (ECMWF)
# SPDX-License-Identifier: Apache-2.0
"""Render docs/upstream/README.md (the issue drafts) from docs/upstream/issues.toml.

python3 scripts/upstream_drafts.py           # write README.md
python3 scripts/upstream_drafts.py --check   # exit 1 if README.md is stale
python3 scripts/upstream_drafts.py --body meteo-wet-bulb-bisect-2d.py
    # print one issue body, ready for: gh issue create -R <repo> --title ... --body-file -
"""

from __future__ import annotations

import sys
from pathlib import Path

import tomllib

UP = Path(__file__).resolve().parents[1] / "docs" / "upstream"
# REUSE-IgnoreStart — a licence header written into generated output, not this file's
HEADER = (
    "<!--\n"
    "SPDX-FileCopyrightText: 2026 European Centre for Medium-Range Weather Forecasts (ECMWF)\n"
    "SPDX-License-Identifier: Apache-2.0\n"
    "GENERATED by scripts/upstream_drafts.py from issues.toml — do not edit.\n"
    "-->\n"
)
# REUSE-IgnoreEnd


def body(i: dict) -> str:
    code = (UP / i["script"]).read_text().rstrip()
    return "\n".join(
        [
            f"**What happens:** {i['actual']}",
            "",
            f"**Expected:** {i['expected']}",
            "",
            "**Reproducer** (self-contained; `uv run --script repro.py`):",
            "",
            "```python",
            code,
            "```",
            "",
            f"**Suggested fix:** {i['suggestion']}",
            "",
            f"**Workaround:** {i.get('workaround', '—')}",
            "",
            "Found while writing verified earthkit recipes for the ECMWF agent skills "
            "(https://github.com/ecmwf/ecmwf-weather-skills).",
        ]
    )


def _status(i: dict) -> str:
    return f"[{i['status']}]({i['url']})" if i.get("url") else i["status"]


def render(issues: list[dict]) -> str:
    rows = [
        f"| {_status(i)} | `{i['repo']}` | {i['title']} | [`{i['script']}`]({i['script']}) |"
        for i in issues
    ]
    parts = [
        HEADER,
        "# Upstream earthkit issues",
        "",
        "Not filed. Each needs the maintainer's approval; then: "
        "`python3 scripts/upstream_drafts.py --body <script> | gh issue create -R <repo> "
        '--title "<title>" --body-file -`, and record `status = "filed"` and `url`.',
        "",
        "| Status | Repository | Title | Reproducer |",
        "|---|---|---|---|",
        *rows,
        "",
    ]
    for i in issues:
        parts += [
            f"## {i['title']}",
            "",
            f"Repository: `{i['repo']}` · {i['kind']} · {_status(i)}",
            "",
            body(i),
            "",
        ]
    return "\n".join(parts).rstrip() + "\n"


def main(argv: list[str]) -> int:
    issues = tomllib.loads((UP / "issues.toml").read_text())["issue"]
    if "--body" in argv:
        name = argv[argv.index("--body") + 1]
        print(body(next(i for i in issues if i["script"] == name)))
        return 0
    text = render(issues)
    if "--check" in argv:
        stale = (UP / "README.md").read_text() != text if (UP / "README.md").exists() else True
        print(
            "docs/upstream/README.md is stale — run scripts/upstream_drafts.py"
            if stale
            else "up to date"
        )
        return 1 if stale else 0
    (UP / "README.md").write_text(text)
    print(f"wrote {len(issues)} drafts")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
